"""
95-modality AI orchestration: /ai/detect-modality, /ai/interrogate, /ai/interpret
"""
from __future__ import annotations

import base64
import hashlib
import io
import json
import logging
import os
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Header, HTTPException
from pydantic import BaseModel, Field

from audit_logger import log_analysis_event
from auth import verify_token

logger = logging.getLogger("manthana.ai_orchestrator")

router = APIRouter(prefix="/ai", tags=["ai-orchestration"])

WEB_SEARCH_PARAMETERS: Dict[str, Any] = {
    "max_results": 3,
    "max_total_results": 6,
    "allowed_domains": [
        "pubmed.ncbi.nlm.nih.gov",
        "ncbi.nlm.nih.gov",
        "nature.com",
        "nejm.org",
        "thelancet.com",
        "rsna.org",
        "arxiv.org",
        "radiopaedia.org",
    ],
}

_DISCLAIMER = {
    "text": (
        "This report is generated by Manthana Labs AI for educational, research, "
        "and retrospective study purposes only. It is a second-opinion tool and does "
        "not constitute medical advice, diagnosis, or treatment. "
        "Review and sign-off by a licensed physician or radiologist is mandatory "
        "before any clinical decision is made based on this output."
    ),
    "version": "1.0",
    "regulatory_note": "SaMD — Not approved for autonomous clinical diagnosis. India MDR 2017 compliant.",
}

TEXT_ONLY_SESSION_GROUPS = frozenset({"reports", "cardiac_functional"})


def _orch_enabled() -> bool:
    return (os.getenv("AI_ORCHESTRATION_ENABLED", "true") or "").strip().lower() in (
        "1",
        "true",
        "yes",
    )


def _require_orch() -> None:
    if not _orch_enabled():
        raise HTTPException(status_code=503, detail="AI orchestration is disabled")


def _strip_json_fence(s: str) -> str:
    s = (s or "").strip()
    if s.startswith("```"):
        s = re.sub(r"^```[a-zA-Z]*\n?", "", s)
        s = re.sub(r"\n?```\s*$", "", s)
    return s.strip()


def _parse_json_obj(s: str) -> Dict[str, Any]:
    raw = _strip_json_fence(s)
    return json.loads(raw)


def _inject_disclaimer(report: Dict[str, Any]) -> Dict[str, Any]:
    report["disclaimer"] = {
        **_DISCLAIMER,
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    return report


def _allowed_orch_groups() -> set[str]:
    raw = (os.environ.get("ORCH_ALLOWED_GROUPS") or "").strip()
    if not raw:
        return set()
    return {g.strip().lower() for g in raw.split(",") if g.strip()}


def _downscale_for_session(image_b64: str, max_px: int = 512) -> str:
    from PIL import Image

    raw = base64.b64decode(image_b64)
    img = Image.open(io.BytesIO(raw)).convert("RGB")
    if max(img.size) > max_px:
        ratio = max_px / max(img.size)
        new_size = (int(img.width * ratio), int(img.height * ratio))
        img = img.resize(new_size, Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=80, optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


def _prepare_session_image(
    converted_b64: Optional[str],
    converted_mime: Optional[str],
    group: str,
) -> tuple[Optional[str], str]:
    if group in TEXT_ONLY_SESSION_GROUPS:
        return None, "image/jpeg"
    if not converted_b64 or not converted_mime:
        return None, "image/jpeg"
    mime = (converted_mime or "").lower()
    if mime not in ("image/png", "image/jpeg", "image/jpg", "image/webp"):
        return None, "image/jpeg"
    return _downscale_for_session(converted_b64), "image/jpeg"


def _preprocess_detect_body(body: "DetectRequest") -> None:
    from dicom_converter import convert_image_for_llm, extract_pdf_text, is_pdf

    if not body.image_b64:
        return
    if is_pdf(body.image_mime):
        try:
            pdf_text = extract_pdf_text(body.image_b64)
        except ValueError as e:
            raise HTTPException(status_code=422, detail=str(e)) from e
        merged = (body.text_context or "").strip()
        merged = (merged + "\n\n[Extracted PDF]\n" + pdf_text).strip()[:12000]
        body.text_context = merged
        body.image_b64 = None
        body.image_mime = "image/jpeg"
        return
    try:
        body.image_b64, body.image_mime = convert_image_for_llm(
            body.image_b64, body.image_mime or "image/jpeg"
        )
    except ValueError as e:
        raise HTTPException(
            status_code=422,
            detail=f"Image conversion failed: {e}. Supported: JPEG, PNG, DICOM, PDF.",
        ) from e


def _preprocess_interrogate_body(body: "InterrogateRequest") -> None:
    from dicom_converter import (
        convert_image_for_llm,
        extract_pdf_text,
        is_pdf,
        merge_pdf_into_patient_context_json,
    )

    if not body.image_b64:
        return
    if is_pdf(body.image_mime):
        try:
            pdf_text = extract_pdf_text(body.image_b64)
        except ValueError as e:
            raise HTTPException(status_code=422, detail=str(e)) from e
        body.image_b64 = None
        body.image_mime = "image/jpeg"
        body.patient_context_json = merge_pdf_into_patient_context_json(
            body.patient_context_json, pdf_text
        )
        return
    try:
        body.image_b64, body.image_mime = convert_image_for_llm(
            body.image_b64, body.image_mime or "image/jpeg"
        )
    except ValueError as e:
        raise HTTPException(
            status_code=422,
            detail=f"Image conversion failed: {e}. Supported: JPEG, PNG, DICOM, PDF.",
        ) from e


def _llm():
    from llm_router import llm_router

    return llm_router


def _interpret_use_web_search(tier: str) -> bool:
    """Labs orchestration interpret: OpenRouter web search policy (default: always)."""
    mode = (os.getenv("AI_ORCH_INTERPRET_WEB_SEARCH") or "always").strip().lower()
    if mode in ("0", "false", "no", "never"):
        return False
    if mode in ("paid_only", "paid", "tier"):
        return tier not in ("", "free", "trial")
    return True


def _orch_input_fingerprint(
    *,
    modality_key: Optional[str],
    image_mime: Optional[str],
    image_b64: Optional[str],
    session_id: Optional[str],
) -> str:
    payload = {
        "modality_key": modality_key or "",
        "mime": image_mime or "",
        "b64_len": len(image_b64 or ""),
        "session": session_id or "",
    }
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _sha256_text(s: str) -> str:
    return hashlib.sha256((s or "").encode("utf-8", errors="replace")).hexdigest()


def _model_version_for_slug(model_slug: str) -> Optional[str]:
    try:
        from manthana_inference.loader import load_cloud_inference_config

        p = (os.environ.get("CLOUD_INFERENCE_CONFIG_PATH") or "").strip()
        cfg = load_cloud_inference_config(Path(p) if p else None)
        mv = getattr(cfg, "model_versions", None) or {}
        return mv.get(model_slug) or mv.get(str(model_slug).split("/")[-1])
    except Exception:
        return None


def _strip_model_disclaimer(report: Dict[str, Any]) -> None:
    """Orchestrator-owned disclaimer only — never trust model-emitted disclaimer."""
    report.pop("disclaimer", None)


def _normalize_finding_confidence_pct(report: Dict[str, Any]) -> None:
    """Ensure structured findings include confidence_pct (0–100) for UI/clinical consistency."""
    findings = report.get("findings")
    if not isinstance(findings, dict):
        return
    for bucket in ("primary", "secondary"):
        arr = findings.get(bucket)
        if not isinstance(arr, list):
            continue
        for item in arr:
            if isinstance(item, dict) and "confidence_pct" not in item:
                item["confidence_pct"] = 50


def _registry():
    from modality_registry import (
        AUTO_DETECT_KEY,
        MODALITY_GROUPS_META,
        MODALITY_REGISTRY,
        get_modality_config,
        list_modalities_for_prompt,
        validate_modality_key,
    )

    return (
        AUTO_DETECT_KEY,
        MODALITY_GROUPS_META,
        MODALITY_REGISTRY,
        get_modality_config,
        list_modalities_for_prompt,
        validate_modality_key,
    )


def _prompts():
    from prompts.interpreter_base import interpret_user_text_block, interpreter_system_prompt
    from prompts.interrogator_base import detect_modality_system_prompt, interrogator_system_prompt
    from prompts.labs_pre_validate_prompt import LAB_PRE_VALIDATE_PROMPT
    from prompts.modality_prompts import group_specialization_for

    return (
        interpret_user_text_block,
        interpreter_system_prompt,
        detect_modality_system_prompt,
        interrogator_system_prompt,
        group_specialization_for,
        LAB_PRE_VALIDATE_PROMPT,
    )


def _session():
    from session_store import session_store

    return session_store


class DetectRequest(BaseModel):
    image_b64: Optional[str] = None
    image_mime: str = Field(default="image/jpeg")
    text_context: Optional[str] = Field(
        default=None,
        description="Optional raw text for report-only classification",
    )


class InterrogateRequest(BaseModel):
    image_b64: Optional[str] = None
    image_mime: str = "image/jpeg"
    modality_key: str
    patient_context_json: Optional[str] = None


class AnswerItem(BaseModel):
    question_id: str
    answer: str


class InterpretRequest(BaseModel):
    session_id: str
    answers: List[AnswerItem]
    patient_context_json: Optional[str] = None


class PreValidateRequest(BaseModel):
    image_b64: Optional[str] = None
    image_mime: Optional[str] = None
    selected_modality: Optional[str] = None
    patient_context: Optional[Dict[str, Any]] = None


class PreValidateChatRequest(BaseModel):
    message: str
    chat_history: List[Dict[str, str]] = Field(default_factory=list)
    validation_context: Dict[str, Any] = Field(default_factory=dict)


def _uid(token_data: dict) -> str:
    return str(token_data.get("sub") or token_data.get("user_id") or "unknown")


def _tier(h: Optional[str]) -> str:
    return (h or "free").strip().lower() or "free"


@router.get("/modalities")
async def list_modalities(
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    _require_orch()
    try:
        _, MODALITY_GROUPS_META, MODALITY_REGISTRY, _, _, _ = _registry()
        items = []
        for k, cfg in sorted(MODALITY_REGISTRY.items(), key=lambda x: (x[1].group, x[0])):
            items.append(
                {
                    "key": k,
                    "group": cfg.group,
                    "display_name": cfg.display_name,
                    "input_formats": list(cfg.input_formats),
                    "interrogator_role": cfg.interrogator_role,
                    "interpreter_role": cfg.interpreter_role,
                }
            )
        log_analysis_event(
            uid,
            "list_modalities",
            subscription_tier=tier,
            success=True,
        )
        return {"groups": MODALITY_GROUPS_META, "modalities": items}
    except HTTPException as e:
        log_analysis_event(
            uid,
            "list_modalities",
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
        )
        raise
    except Exception as e:
        logger.exception("list_modalities: %s", e)
        log_analysis_event(
            uid,
            "list_modalities",
            subscription_tier=tier,
            success=False,
            error_code=502,
        )
        raise HTTPException(status_code=502, detail=str(e)) from e


@router.post("/pre-validate")
async def pre_validate(
    body: PreValidateRequest,
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    _require_orch()
    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    _, _, _, _, _, _ = _registry()
    (_, _, _, _, _, LAB_PRE_VALIDATE_PROMPT) = _prompts()
    llm = _llm()
    pc = json.dumps(body.patient_context or {}, ensure_ascii=False, indent=2)
    user_prompt = (
        LAB_PRE_VALIDATE_PROMPT.replace("{{selectedModality}}", body.selected_modality or "unknown")
        .replace("{{patientContext}}", pc)
    )
    try:
        if body.image_b64 and (body.image_mime or "").strip():
            r = llm.complete_for_role(
                role="labs_pre_validate",
                system_prompt="You output only valid JSON as specified in the user message.",
                user_text=user_prompt,
                requires_json=True,
                image_b64=body.image_b64,
                image_mime=body.image_mime or "image/jpeg",
            )
        else:
            r = llm.complete_for_role(
                role="labs_pre_validate",
                system_prompt="You output only valid JSON as specified in the user message.",
                user_text=user_prompt,
                requires_json=True,
            )
        data = _parse_json_obj(r.get("content") or "{}")
        log_analysis_event(
            uid,
            "pre_validate",
            modality_key=body.selected_modality,
            subscription_tier=tier,
            model_used=str(r.get("model_used")),
            success=True,
            image_mime=body.image_mime,
        )
        return {"raw": data, "model_used": r.get("model_used"), "usage": r.get("usage") or {}}
    except HTTPException as e:
        log_analysis_event(
            uid,
            "pre_validate",
            modality_key=body.selected_modality,
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
            image_mime=body.image_mime,
        )
        raise
    except Exception as e:
        logger.exception("pre_validate failed: %s", e)
        log_analysis_event(
            uid,
            "pre_validate",
            modality_key=body.selected_modality,
            subscription_tier=tier,
            success=False,
            error_code=502,
            image_mime=body.image_mime,
        )
        raise HTTPException(status_code=502, detail=str(e)) from e


@router.post("/pre-validate-chat")
async def pre_validate_chat(
    body: PreValidateChatRequest,
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    _require_orch()
    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    ctx = body.validation_context
    sys_p = (
        "You are an expert radiology AI assistant helping a user analyze a medical study.\n"
        f"Context — file type: {ctx.get('fileType') or ctx.get('file_type', '')}, "
        f"detected modality: {ctx.get('detectedModality') or ctx.get('detected_modality', '')}, "
        f"selected modality: {ctx.get('selectedModality') or ctx.get('selected_modality', '')}, "
        f"image quality: {ctx.get('imageQuality') or ctx.get('image_quality', '')}, "
        f"provisional opinion: {ctx.get('provisionalOpinion') or ctx.get('provisional_opinion', '')}.\n"
        "Be concise and clinical."
    )
    lines: List[str] = []
    for h in body.chat_history or []:
        role = h.get("role", "user")
        label = "Assistant" if role in ("ai", "assistant") else "User"
        lines.append(f"{label}: {h.get('content', '')}")
    lines.append(f"User: {body.message}")
    user_block = "\n".join(lines)
    llm = _llm()
    try:
        r = llm.complete_for_role(
            role="labs_validation_chat",
            system_prompt=sys_p,
            user_text=user_block,
            requires_json=False,
        )
        log_analysis_event(
            uid,
            "pre_validate_chat",
            subscription_tier=tier,
            model_used=str(r.get("model_used")),
            success=True,
        )
        return {"content": r.get("content") or "", "model_used": r.get("model_used")}
    except HTTPException as e:
        log_analysis_event(
            uid,
            "pre_validate_chat",
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
        )
        raise
    except Exception as e:
        logger.exception("pre_validate_chat failed: %s", e)
        log_analysis_event(
            uid,
            "pre_validate_chat",
            subscription_tier=tier,
            success=False,
            error_code=502,
        )
        raise HTTPException(status_code=502, detail=str(e)) from e


@router.post("/detect-modality")
async def detect_modality(
    body: DetectRequest,
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    _require_orch()
    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    (
        _auto,
        _gm,
        _reg,
        _get,
        list_for_prompt,
        _val,
    ) = _registry()
    (
        _iub,
        _interp_sys,
        detect_sys,
        _iq_sys,
        _gs,
        _lab,
    ) = _prompts()

    if not body.image_b64 and not (body.text_context or "").strip():
        raise HTTPException(status_code=400, detail="image_b64 or text_context required")

    try:
        _preprocess_detect_body(body)
    except HTTPException:
        raise

    llm = _llm()
    modality_list = list_for_prompt()
    system = detect_sys(modality_list_text=modality_list)
    user_text = "Classify this study."
    if body.text_context and not body.image_b64:
        user_text = f"Document text (excerpt):\n{(body.text_context or '')[:12000]}"

    try:
        t0 = time.perf_counter()
        if body.image_b64:
            r = llm.complete_for_role_chain(
                "modality_detect",
                system,
                user_text,
                requires_json=True,
                image_b64=body.image_b64,
                image_mime=body.image_mime or "image/jpeg",
                use_web_on_first_openrouter=False,
                fallback_single_role="modality_detect",
            )
        else:
            r = llm.complete_for_role_chain(
                "modality_detect",
                system,
                user_text,
                requires_json=True,
                use_web_on_first_openrouter=False,
                fallback_single_role="modality_detect",
            )
        data = _parse_json_obj(r.get("content") or "{}")
        latency_ms = int((time.perf_counter() - t0) * 1000)
        cm = r.get("chain_meta") or {}
        in_hash = _orch_input_fingerprint(
            modality_key=str(data.get("modality_key")),
            image_mime=body.image_mime,
            image_b64=body.image_b64,
            session_id=None,
        )
        out_hash = _sha256_text(str(r.get("content") or ""))
        log_analysis_event(
            uid,
            "detect",
            modality_key=str(data.get("modality_key")),
            group=str(data.get("group")) if data.get("group") else None,
            subscription_tier=tier,
            model_used=str(r.get("model_used")),
            success=True,
            image_mime=body.image_mime,
            stage="detect",
            chain_key="modality_detect",
            latency_ms=latency_ms,
            input_sha256=in_hash,
            output_sha256=out_hash,
            web_search_used=bool(cm.get("web_search_used")),
            chain_attempts=cm.get("attempts"),
            model_version=_model_version_for_slug(str(r.get("model_used") or "")),
        )
    except HTTPException as e:
        log_analysis_event(
            uid,
            "detect",
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
            image_mime=body.image_mime,
        )
        raise
    except Exception as e:
        logger.exception("detect-modality failed: %s", e)
        log_analysis_event(
            uid,
            "detect",
            subscription_tier=tier,
            success=False,
            error_code=502,
            image_mime=body.image_mime,
        )
        raise HTTPException(status_code=502, detail=str(e)) from e

    return {
        "modality_key": data.get("modality_key", "unknown"),
        "confidence": float(data.get("confidence") or 0),
        "group": data.get("group"),
        "reason": data.get("reason"),
        "model_used": r.get("model_used"),
    }


@router.post("/interrogate")
async def interrogate(
    body: InterrogateRequest,
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    _require_orch()
    from rate_limiter import enforce_rate_limit

    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    enforce_rate_limit(uid, tier)

    _, _, _, get_modality_config, _, validate_modality_key = _registry()
    (
        _iub,
        _interp_sys,
        _det,
        interrogator_system_prompt,
        _group_spec,
        _lab,
    ) = _prompts()
    store = _session()

    mk = (body.modality_key or "").strip().lower()
    if mk in ("auto", ""):
        raise HTTPException(
            status_code=400,
            detail="modality_key is required (use /detect-modality first for auto)",
        )
    if not validate_modality_key(mk):
        raise HTTPException(status_code=422, detail=f"Unknown modality_key: {mk}")

    cfg = get_modality_config(mk)
    if not cfg:
        raise HTTPException(status_code=422, detail="Invalid modality")

    allowed = _allowed_orch_groups()
    if allowed and cfg.group.lower() not in allowed:
        raise HTTPException(
            status_code=403,
            detail={
                "error": f"Modality group '{cfg.group}' is not yet available in this release.",
                "message": (
                    "This feature is coming soon. Currently available: reports, "
                    "prescriptions, lab results, ECG analysis."
                ),
                "group_requested": cfg.group,
            },
        )

    try:
        _preprocess_interrogate_body(body)
    except HTTPException:
        raise

    img_for_session_b64 = body.image_b64
    img_for_session_mime = body.image_mime or "image/jpeg"

    sys_p = interrogator_system_prompt(modality_key=cfg.key, display_name=cfg.display_name)
    user_t = "Generate questions JSON as specified."
    lr = _llm()
    r: Dict[str, Any]
    interrogator_model: str
    _interrogate_latency_ms = 0
    _interrogate_cm: Dict[str, Any] = {}
    _interrogate_in_hash = ""
    _interrogate_out_hash = ""
    try:
        t0 = time.perf_counter()
        chain_key = cfg.interrogator_role
        if body.image_b64:
            r = lr.complete_for_role_chain(
                chain_key,
                sys_p,
                user_t,
                requires_json=True,
                image_b64=body.image_b64,
                image_mime=body.image_mime or "image/jpeg",
                use_web_on_first_openrouter=False,
                fallback_single_role=cfg.interrogator_role,
            )
        else:
            r = lr.complete_for_role_chain(
                chain_key,
                sys_p,
                user_text=(body.patient_context_json or "No extra text.")[:16000],
                requires_json=True,
                use_web_on_first_openrouter=False,
                fallback_single_role=cfg.interrogator_role,
            )
        interrogator_model = str(r.get("model_used", ""))
        _interrogate_latency_ms = int((time.perf_counter() - t0) * 1000)
        _interrogate_cm = r.get("chain_meta") or {}
        _interrogate_in_hash = _orch_input_fingerprint(
            modality_key=cfg.key,
            image_mime=body.image_mime,
            image_b64=body.image_b64,
            session_id=None,
        )
        _interrogate_out_hash = _sha256_text(str(r.get("content") or ""))
        qdata = _parse_json_obj(r.get("content") or "{}")
        questions = qdata.get("questions") or []
    except HTTPException as e:
        log_analysis_event(
            uid,
            "interrogate",
            modality_key=cfg.key,
            group=cfg.group,
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
            image_mime=body.image_mime,
        )
        raise
    except Exception as e:
        logger.exception("interrogate failed: %s", e)
        log_analysis_event(
            uid,
            "interrogate",
            modality_key=cfg.key,
            group=cfg.group,
            subscription_tier=tier,
            success=False,
            error_code=502,
            image_mime=body.image_mime,
        )
        raise HTTPException(status_code=502, detail=str(e)) from e

    sess_b64, sess_mime = _prepare_session_image(
        img_for_session_b64,
        img_for_session_mime,
        cfg.group,
    )

    sid = store.create(
        image_b64=sess_b64,
        image_mime=sess_mime,
        modality_key=cfg.key,
        display_name=cfg.display_name,
        group=cfg.group,
        questions=questions,
        interrogator_model=interrogator_model,
        interpreter_role=cfg.interpreter_role,
        patient_context_json=body.patient_context_json,
    )
    log_analysis_event(
        uid,
        "interrogate",
        modality_key=cfg.key,
        group=cfg.group,
        subscription_tier=tier,
        model_used=str(r.get("model_used")),
        success=True,
        image_mime=body.image_mime,
        session_id=sid,
        stage="interrogate",
        chain_key=cfg.interrogator_role,
        latency_ms=_interrogate_latency_ms or None,
        input_sha256=_interrogate_in_hash or None,
        output_sha256=_interrogate_out_hash or None,
        web_search_used=bool(_interrogate_cm.get("web_search_used")),
        chain_attempts=_interrogate_cm.get("attempts"),
        model_version=_model_version_for_slug(str(r.get("model_used") or "")),
    )
    return {
        "session_id": sid,
        "questions": questions,
        "model_used": r.get("model_used"),
        "modality_key": cfg.key,
    }


@router.post("/interpret")
async def interpret(
    body: InterpretRequest,
    token_data: dict = Depends(verify_token),
    x_subscription_tier: Optional[str] = Header(None, alias="X-Subscription-Tier"),
):
    _require_orch()
    uid = _uid(token_data)
    tier = _tier(x_subscription_tier)
    _, _, _, get_modality_config, _, _ = _registry()
    (
        interpret_user_text_block,
        interpreter_system_prompt,
        _d,
        _iq,
        group_specialization_for,
        _lab,
    ) = _prompts()
    store = _session()

    row = store.get(body.session_id)
    if not row:
        log_analysis_event(
            uid,
            "interpret",
            subscription_tier=tier,
            success=False,
            error_code=404,
            session_id=body.session_id,
        )
        raise HTTPException(status_code=404, detail="Session expired or not found")

    mk = row["modality_key"]
    cfg = get_modality_config(mk)
    if not cfg:
        store.delete(body.session_id)
        log_analysis_event(
            uid,
            "interpret",
            modality_key=mk,
            subscription_tier=tier,
            success=False,
            error_code=500,
            session_id=body.session_id,
        )
        raise HTTPException(status_code=500, detail="Session modality invalid")

    enable_web = _interpret_use_web_search(tier)

    qa_json = json.dumps([a.model_dump() for a in body.answers], ensure_ascii=False)
    pc = body.patient_context_json or row.get("patient_context_json")

    sys_p = interpreter_system_prompt(
        modality_key=cfg.key,
        display_name=cfg.display_name,
        group=cfg.group,
        group_extra=group_specialization_for(cfg.group),
        enable_web_search=enable_web,
    )
    user_t = interpret_user_text_block(qa_pairs_json=qa_json, patient_context_json=pc)

    llm = _llm()
    r: Dict[str, Any]
    _interpret_latency_ms = 0
    _interpret_cm: Dict[str, Any] = {}
    _interpret_in_hash = ""
    _interpret_out_hash = ""
    chain_key = cfg.interpreter_role
    try:
        img = row.get("image_b64")
        mime = row.get("image_mime") or "image/jpeg"
        t0 = time.perf_counter()
        r = llm.complete_for_role_chain(
            chain_key,
            sys_p,
            user_t,
            requires_json=True,
            image_b64=img,
            image_mime=mime,
            web_search_parameters=WEB_SEARCH_PARAMETERS if enable_web else None,
            use_web_on_first_openrouter=enable_web,
            fallback_single_role=cfg.interpreter_role,
        )
        _interpret_latency_ms = int((time.perf_counter() - t0) * 1000)
        _interpret_cm = r.get("chain_meta") or {}
        _interpret_in_hash = _orch_input_fingerprint(
            modality_key=cfg.key,
            image_mime=mime,
            image_b64=img,
            session_id=body.session_id,
        )
        _interpret_out_hash = _sha256_text(str(r.get("content") or ""))

        raw_content = r.get("content") or "{}"
        try:
            parsed = _parse_json_obj(str(raw_content))
        except (json.JSONDecodeError, TypeError, ValueError):
            report = {"report_text": _strip_json_fence(str(raw_content))}
        else:
            report = parsed if isinstance(parsed, dict) else {"report_text": str(parsed)}
        if isinstance(report, dict):
            _strip_model_disclaimer(report)
            _normalize_finding_confidence_pct(report)
        report.setdefault("models_used", [])
        if isinstance(report["models_used"], list):
            report["models_used"] = list(report["models_used"]) + [str(r.get("model_used"))]
        report = _inject_disclaimer(report)
    except HTTPException as e:
        log_analysis_event(
            uid,
            "interpret",
            modality_key=cfg.key,
            group=cfg.group,
            subscription_tier=tier,
            success=False,
            error_code=e.status_code,
            session_id=body.session_id,
            stage="interpret",
            chain_key=chain_key,
        )
        raise
    except Exception as e:
        logger.exception("interpret failed: %s", e)
        log_analysis_event(
            uid,
            "interpret",
            modality_key=cfg.key,
            group=cfg.group,
            subscription_tier=tier,
            success=False,
            error_code=502,
            session_id=body.session_id,
            stage="interpret",
            chain_key=chain_key,
            latency_ms=_interpret_latency_ms or None,
            web_search_used=bool(_interpret_cm.get("web_search_used")),
            chain_attempts=_interpret_cm.get("attempts"),
        )
        raise HTTPException(status_code=502, detail=str(e)) from e
    finally:
        store.delete(body.session_id)

    log_analysis_event(
        uid,
        "interpret",
        modality_key=cfg.key,
        group=cfg.group,
        subscription_tier=tier,
        model_used=str(r.get("model_used")),
        success=True,
        session_id=body.session_id,
        stage="interpret",
        chain_key=chain_key,
        latency_ms=_interpret_latency_ms or None,
        input_sha256=_interpret_in_hash or None,
        output_sha256=_interpret_out_hash or None,
        web_search_used=bool(_interpret_cm.get("web_search_used")),
        chain_attempts=_interpret_cm.get("attempts"),
        model_version=_model_version_for_slug(str(r.get("model_used") or "")),
    )
    return {
        "report": report,
        "model_used": r.get("model_used"),
        "web_search_enabled": enable_web,
        "usage": r.get("usage") or {},
    }
